### ISSUE TITLE
Mejorar los componentes tipo combobox

### ISSUE THREAD

**Issue by vieraleonel** [robysottini/taller#3]
En todos los formularios de carga donde se utilizan los componentes \<select>, mejorarlos con una librería que ayude al usuario. Por ejemplo: [select2](https://select2.github.io/)

**Comment by robysottini** [comment]
Usé el componente [Select2] (https://select2.github.io/).
Modifiqué estos archivos:

1. **app/Resources/views/base.html.twig**.
2. **src/AppBundle/Form/PuntoInteresType.php**.
